I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/day1morning.rpy", line 54, in script
    $ add_intellectual_score(1)
  File "game/story/day1morning.rpy", line 54, in <module>
    $ add_intellectual_score(1)
  File "game/script.rpy", line 44, in add_intellectual_score
    if prev_trait == 'Intellectual':
UnboundLocalError: local variable 'prev_trait' referenced before assignment

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/day1morning.rpy", line 54, in script
    $ add_intellectual_score(1)
  File "C:\Users\thesh\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\thesh\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/story/day1morning.rpy", line 54, in <module>
    $ add_intellectual_score(1)
  File "game/script.rpy", line 44, in add_intellectual_score
    if prev_trait == 'Intellectual':
UnboundLocalError: local variable 'prev_trait' referenced before assignment

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.1.23060707
Breaking the Ice 1.0
Sat Jul  1 10:29:26 2023
