I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/story/mugging.rpy", line 31, in script
    show mugger with dissolve_sustained
  File "game/story/mugging.rpy", line 31, in <module>
    show mugger with dissolve_sustained
NameError: name 'dissolve_sustained' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/story/mugging.rpy", line 31, in script
    show mugger with dissolve_sustained
  File "C:\Users\thesh\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 1654, in execute
    paired = renpy.python.py_eval(self.paired)
  File "C:\Users\thesh\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\thesh\Desktop\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/story/mugging.rpy", line 31, in <module>
    show mugger with dissolve_sustained
NameError: name 'dissolve_sustained' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
Breaking the Ice 1.0
Tue Jun 27 11:19:19 2023
